export var GROUP_FILTER;
(function (GROUP_FILTER) {
    GROUP_FILTER[GROUP_FILTER["ATIVIDADE"] = 0] = "ATIVIDADE";
    GROUP_FILTER[GROUP_FILTER["DIA"] = 1] = "DIA";
    GROUP_FILTER[GROUP_FILTER["TURMA"] = 2] = "TURMA";
    GROUP_FILTER[GROUP_FILTER["PROGRAM"] = 3] = "PROGRAM";
})(GROUP_FILTER || (GROUP_FILTER = {}));
//# sourceMappingURL=constants.js.map