export var ENTITIES;
(function (ENTITIES) {
    ENTITIES[ENTITIES["TAG"] = 0] = "TAG";
    ENTITIES[ENTITIES["PERSON"] = 1] = "PERSON";
    ENTITIES[ENTITIES["SPACE"] = 2] = "SPACE";
    ENTITIES[ENTITIES["FINITE_RESOURCES"] = 3] = "FINITE_RESOURCES";
    ENTITIES[ENTITIES["INFINITE_RESOURCES"] = 4] = "INFINITE_RESOURCES";
    ENTITIES[ENTITIES["ACADEMIC_ACTIVITY"] = 5] = "ACADEMIC_ACTIVITY";
    ENTITIES[ENTITIES["NON_ACADEMIC_ACTIVITY"] = 6] = "NON_ACADEMIC_ACTIVITY";
    ENTITIES[ENTITIES["INTERNAL_ACTIVITY"] = 7] = "INTERNAL_ACTIVITY";
    ENTITIES[ENTITIES["PROGRAM"] = 8] = "PROGRAM";
    ENTITIES[ENTITIES["PROGRAM_MODEL"] = 9] = "PROGRAM_MODEL";
    ENTITIES[ENTITIES["TEAM"] = 10] = "TEAM";
    ENTITIES[ENTITIES["TEAM_MODEL"] = 11] = "TEAM_MODEL";
    ENTITIES[ENTITIES["SCHEDULE"] = 12] = "SCHEDULE";
    ENTITIES[ENTITIES["SCHEDULE_MODEL"] = 13] = "SCHEDULE_MODEL";
    ENTITIES[ENTITIES["ACTIVITY"] = 14] = "ACTIVITY";
    ENTITIES[ENTITIES["ACTIVITY_MODEL"] = 15] = "ACTIVITY_MODEL";
})(ENTITIES || (ENTITIES = {}));
//# sourceMappingURL=constants.js.map