export var AVAILABILITY;
(function (AVAILABILITY) {
    AVAILABILITY["CONFLITO"] = "CONFLITO";
    AVAILABILITY["PARCIALMENTE_LIVRE"] = "PARCIALMENTE_LIVRE";
    AVAILABILITY["TOTALMENTE_LIVRE"] = "TOTALMENTE_LIVRE";
})(AVAILABILITY || (AVAILABILITY = {}));
//# sourceMappingURL=constants.js.map