# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- homolog

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.20'
  displayName: 'Install Node.js'

- script: |
    yarn install --ignore-engines
  displayName: 'yarn install'

- script: |
    yarn run build:hml
  displayName: 'yarn build:hml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'sharepoint/solution/ise-apps-hml.sppkg'
    ArtifactName: 'app'
    publishLocation: 'Container'
  displayName: 'publish app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'certificates'
    ArtifactName: 'certificates'
    publishLocation: 'Container'
  displayName: 'publish certificates'